// flow-typed signature: 31804123048d0b042f241e053da91d66
// flow-typed version: <<STUB>>/eslint-plugin-testing-library_v^7.16.0/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-testing-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-testing-library' {
  declare module.exports: any;
}
