// flow-typed signature: 25ff095f9204a204e763db0903e861ec
// flow-typed version: <<STUB>>/@babel/cli_v^8.0.4/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/cli/bin/babel' {
  declare module.exports: any;
}

declare module '@babel/cli/lib/babel' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/cli/bin/babel.js' {
  declare module.exports: $Exports<'@babel/cli/bin/babel'>;
}
declare module '@babel/cli/lib/babel/index' {
  declare module.exports: $Exports<'@babel/cli/lib/babel'>;
}
declare module '@babel/cli/lib/babel/index.js' {
  declare module.exports: $Exports<'@babel/cli/lib/babel'>;
}
