// flow-typed signature: db247a18ddac4978814480fdb3d47ba2
// flow-typed version: <<STUB>>/@babel/core_v^8.0.1/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/core/lib/caching-shared' {
  declare module.exports: any;
}

declare module '@babel/core/lib/config/caching' {
  declare module.exports: any;
}

declare module '@babel/core/lib/config/files/index-browser' {
  declare module.exports: any;
}

declare module '@babel/core/lib/config/files' {
  declare module.exports: any;
}

declare module '@babel/core/lib/config/resolve-targets-browser' {
  declare module.exports: any;
}

declare module '@babel/core/lib/config/resolve-targets' {
  declare module.exports: any;
}

declare module '@babel/core/lib/errors/rewrite-stack-trace' {
  declare module.exports: any;
}

declare module '@babel/core/lib/fs-shared' {
  declare module.exports: any;
}

declare module '@babel/core/lib/index-shared' {
  declare module.exports: any;
}

declare module '@babel/core/lib' {
  declare module.exports: any;
}

declare module '@babel/core/lib/transform-file-browser' {
  declare module.exports: any;
}

declare module '@babel/core/lib/transform-file' {
  declare module.exports: any;
}

declare module '@babel/core/lib/transformation/read-input-source-map-file-browser' {
  declare module.exports: any;
}

declare module '@babel/core/lib/transformation/read-input-source-map-file' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/core/lib/caching-shared.js' {
  declare module.exports: $Exports<'@babel/core/lib/caching-shared'>;
}
declare module '@babel/core/lib/config/caching.js' {
  declare module.exports: $Exports<'@babel/core/lib/config/caching'>;
}
declare module '@babel/core/lib/config/files/index-browser.js' {
  declare module.exports: $Exports<'@babel/core/lib/config/files/index-browser'>;
}
declare module '@babel/core/lib/config/files/index' {
  declare module.exports: $Exports<'@babel/core/lib/config/files'>;
}
declare module '@babel/core/lib/config/files/index.js' {
  declare module.exports: $Exports<'@babel/core/lib/config/files'>;
}
declare module '@babel/core/lib/config/resolve-targets-browser.js' {
  declare module.exports: $Exports<'@babel/core/lib/config/resolve-targets-browser'>;
}
declare module '@babel/core/lib/config/resolve-targets.js' {
  declare module.exports: $Exports<'@babel/core/lib/config/resolve-targets'>;
}
declare module '@babel/core/lib/errors/rewrite-stack-trace.js' {
  declare module.exports: $Exports<'@babel/core/lib/errors/rewrite-stack-trace'>;
}
declare module '@babel/core/lib/fs-shared.js' {
  declare module.exports: $Exports<'@babel/core/lib/fs-shared'>;
}
declare module '@babel/core/lib/index-shared.js' {
  declare module.exports: $Exports<'@babel/core/lib/index-shared'>;
}
declare module '@babel/core/lib/index' {
  declare module.exports: $Exports<'@babel/core/lib'>;
}
declare module '@babel/core/lib/index.js' {
  declare module.exports: $Exports<'@babel/core/lib'>;
}
declare module '@babel/core/lib/transform-file-browser.js' {
  declare module.exports: $Exports<'@babel/core/lib/transform-file-browser'>;
}
declare module '@babel/core/lib/transform-file.js' {
  declare module.exports: $Exports<'@babel/core/lib/transform-file'>;
}
declare module '@babel/core/lib/transformation/read-input-source-map-file-browser.js' {
  declare module.exports: $Exports<'@babel/core/lib/transformation/read-input-source-map-file-browser'>;
}
declare module '@babel/core/lib/transformation/read-input-source-map-file.js' {
  declare module.exports: $Exports<'@babel/core/lib/transformation/read-input-source-map-file'>;
}
