// flow-typed signature: d6fff6ff84b0b6aa0dad699e32738a4a
// flow-typed version: <<STUB>>/@babel/eslint-parser_v^7.16.5 || ^8.0.0/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/eslint-parser/lib/configuration-shared' {
  declare module.exports: any;
}

declare module '@babel/eslint-parser/lib' {
  declare module.exports: any;
}

declare module '@babel/eslint-parser/lib/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/eslint-parser/lib/configuration-shared.js' {
  declare module.exports: $Exports<'@babel/eslint-parser/lib/configuration-shared'>;
}
declare module '@babel/eslint-parser/lib/index' {
  declare module.exports: $Exports<'@babel/eslint-parser/lib'>;
}
declare module '@babel/eslint-parser/lib/index.js' {
  declare module.exports: $Exports<'@babel/eslint-parser/lib'>;
}
declare module '@babel/eslint-parser/lib/worker/index' {
  declare module.exports: $Exports<'@babel/eslint-parser/lib/worker'>;
}
declare module '@babel/eslint-parser/lib/worker/index.js' {
  declare module.exports: $Exports<'@babel/eslint-parser/lib/worker'>;
}
