// flow-typed signature: 165e336de1465bc90cbbe263631093c3
// flow-typed version: <<STUB>>/@babel/preset-env_v^8.0.2/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/preset-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/preset-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/preset-env/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/preset-env/lib/index' {
  declare module.exports: $Exports<'@babel/preset-env/lib'>;
}
declare module '@babel/preset-env/lib/index.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib'>;
}
