// flow-typed signature: e0b60217bced024466e9d93e7fec7082
// flow-typed version: <<STUB>>/@babel/register_v^8.0.1/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/register'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/register' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/register/lib' {
  declare module.exports: any;
}

declare module '@babel/register/lib/types-shared' {
  declare module.exports: any;
}

declare module '@babel/register/lib/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/register/lib/index' {
  declare module.exports: $Exports<'@babel/register/lib'>;
}
declare module '@babel/register/lib/index.js' {
  declare module.exports: $Exports<'@babel/register/lib'>;
}
declare module '@babel/register/lib/types-shared.js' {
  declare module.exports: $Exports<'@babel/register/lib/types-shared'>;
}
declare module '@babel/register/lib/worker/index' {
  declare module.exports: $Exports<'@babel/register/lib/worker'>;
}
declare module '@babel/register/lib/worker/index.js' {
  declare module.exports: $Exports<'@babel/register/lib/worker'>;
}
